spring:
  application:
    name: multithreaded-http-fileserver
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  
  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
logging:
  level:
    root: INFO
    com.goMaddy.multithreaded_http_fileserver: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

  file:
    name: logs/file-server.log    
servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
app:
  upload:
    path: uploads

  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}

  thread-pool:
    size: 10  
  rate-limit:
    capacity: 50
    refill-tokens: 50
    refill-duration: 1  
